### ISSUE TITLE
Some assertions are failing due to inheritance

### ISSUE THREAD

**Issue by rakshitkr** [CROSSINGTUD/CryptoAnalysis#110] opened 2019-01-31 13:05 UTC
The `hasEnsuredPredicate` and `mustBeInAcceptingState` assertions fails for test case [testMac1](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/bouncy_castle/CryptoAnalysis/src/test/java/tests/pattern/MacTest.java) if we replace reference type from `CBCBlockCipherMac` to `Mac`.

```
...
Mac mac = new CBCBlockCipherMac(cipher);
mac.init(key);
mac.update(input1, 0, input1.length);
byte[]  out = new byte[4];
mac.doFinal(out, 0);
Assertions.hasEnsuredPredicate(mac); // fails
Assertions.mustBeInAcceptingState(mac); // fails
```

The corresponding crySL rules for `CBCBlockCipherMac` and `MacBC`can be found at [link1](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/bouncy_castle/src/de/darmstadt/tu/crossing/bc/CBCBlockCipherMac.cryptsl) and [link2](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/bouncy_castle/src/de/darmstadt/tu/crossing/bc/MacBC.cryptsl) respectively.

REASON BEHIND FAILURE:
The analysis considers `CBCBlockCipherMac` crySL rule while executing the below statement
```
Mac mac = new CBCBlockCipherMac(cipher);
```
Whereas it considers `MacBC` rule for the following statements
```
mac.init(key);
mac.update(input1, 0, input1.length);
...
mac.doFinal(out, 0);
```
Since `MacBC` crySL rule is written for a interface, it doesn't have any constructor event corresponding to `CBCBlockCipherMac(cipher)` in `EVENTS` block. It is going into error state because the FSM for `MacBC` doesn't have any edge for `CBCBlockCipherMac (cipher)` event. Hence the assertions fail.

The same assertions pass when we modify the code as below
```
CBCBlockCipherMac mac = new CBCBlockCipherMac(cipher);
```
OR
```
Mac mac = null;
```

**Comment by rbonifacio** [comment] 2019-02-04 13:38
After discussing this issue with Rakshit last week (and thinking a bit more during the weekend), I wonder: what is the semantics of CrySL in the presence of inheritance? In the case that a subclass has its own CrySL specification, should we use the subclass specification or the superclass specification (when we declared the object as having the supertype). 

Perhaps we should also consider how the community of design by contract deals with inheritance. I mean, the CrySL specification of a subclass might completely chance the specification of the superclass?

**Comment by johspaeth** [comment] 2019-02-04 16:33
Yes, that is correct. Inheritance is complete ignored at the moment. We expect that all methods listed in EVENTS are declared within the same class as given by SPEC. @kruegers We have to furher expand and clarify the semantics of the language here.

**Comment by johspaeth** [comment] 2019-02-05 09:19
@rbonifacio the current implemented logic is, that at constructors, even when the declared type differs, e.g., 
`Mac mac = new CBCBlockCipherMac(cipher);`, the exact rule (CBCBlockCipherMac) is chosen. 
I have merged the changes into the master.

**Comment by rakshitkr** [comment] 2019-02-05 12:57
Some test cases in [AESTest.java](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/bouncy_castle/CryptoAnalysis/src/test/java/tests/pattern/AESTest.java) are failing due to ensured predicates not generated.

**Comment by johspaeth** [comment] 2019-02-05 14:06
The failing test case are related to an incorrect translated typestate machine for the rule.
I opened #119, and close this one again.
@rakshitkr In the future, please try to debug the issue and try to locate the root cause for the problem.

**Closed by johspaeth** 2019-02-05 14:06 UTC
Labels: bug
